"""Add league_id to player table

Revision ID: 0fb23e45e086
Revises: 2d66e90305ee
Create Date: 2025-07-23 20:19:11.396889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb23e45e086'
down_revision: Union[str, Sequence[str], None] = '2d66e90305ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'leagues', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'league_id')
    # ### end Alembic commands ###
