"""Enhance league model with tournament formats and flexible scheduling

Revision ID: 12a32c7ace3b
Revises: 8458173d4229
Create Date: 2025-07-23 20:33:17.749319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a32c7ace3b'
down_revision: Union[str, Sequence[str], None] = '8458173d4229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('leagues', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('leagues', sa.Column('tournament_format', sa.String(), nullable=False))
    op.add_column('leagues', sa.Column('regular_season_weeks', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('playoff_weeks', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('swiss_rounds', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('swiss_pairing_method', sa.String(), nullable=True))
    op.add_column('leagues', sa.Column('compass_draw_rounds', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('playoff_teams', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('playoff_format', sa.String(), nullable=True))
    op.add_column('leagues', sa.Column('game_duration', sa.Integer(), nullable=False))
    op.add_column('leagues', sa.Column('games_per_week', sa.Integer(), nullable=False))
    op.add_column('leagues', sa.Column('max_teams', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('min_teams', sa.Integer(), nullable=False))
    op.add_column('leagues', sa.Column('registration_deadline', sa.Date(), nullable=True))
    op.add_column('leagues', sa.Column('registration_fee', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'settings')
    op.drop_column('leagues', 'registration_fee')
    op.drop_column('leagues', 'registration_deadline')
    op.drop_column('leagues', 'min_teams')
    op.drop_column('leagues', 'max_teams')
    op.drop_column('leagues', 'games_per_week')
    op.drop_column('leagues', 'game_duration')
    op.drop_column('leagues', 'playoff_format')
    op.drop_column('leagues', 'playoff_teams')
    op.drop_column('leagues', 'compass_draw_rounds')
    op.drop_column('leagues', 'swiss_pairing_method')
    op.drop_column('leagues', 'swiss_rounds')
    op.drop_column('leagues', 'playoff_weeks')
    op.drop_column('leagues', 'regular_season_weeks')
    op.drop_column('leagues', 'tournament_format')
    op.drop_column('leagues', 'end_date')
    op.drop_column('leagues', 'description')
    # ### end Alembic commands ###
