"""Add profile fields to player table

Revision ID: 2d66e90305ee
Revises: 1f10bc911cb8
Create Date: 2025-07-23 20:04:26.137100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d66e90305ee'
down_revision: Union[str, Sequence[str], None] = '1f10bc911cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('players', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('players', sa.Column('communications_accepted', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('registration_status', sa.String(), nullable=True))
    op.add_column('players', sa.Column('team_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('players', sa.Column('waiver_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'waiver_status')
    op.drop_column('players', 'payment_status')
    op.drop_column('players', 'registration_date')
    op.drop_column('players', 'group_name')
    op.drop_column('players', 'team_name')
    op.drop_column('players', 'registration_status')
    op.drop_column('players', 'communications_accepted')
    op.drop_column('players', 'gender')
    op.drop_column('players', 'date_of_birth')
    op.drop_column('players', 'phone')
    # ### end Alembic commands ###
