"""Replace team_name with team_id foreign key in player table

Revision ID: 8458173d4229
Revises: 0fb23e45e086
Create Date: 2025-07-23 20:22:06.308222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8458173d4229'
down_revision: Union[str, Sequence[str], None] = '0fb23e45e086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    op.drop_column('players', 'team_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'team_id')
    # ### end Alembic commands ###
