"""Add admin config table

Revision ID: ccfe5d949d6b
Revises: 12a32c7ace3b
Create Date: 2025-07-23 20:38:13.179077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfe5d949d6b'
down_revision: Union[str, Sequence[str], None] = '12a32c7ace3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_configs_email'), 'admin_configs', ['email'], unique=True)
    op.create_index(op.f('ix_admin_configs_id'), 'admin_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_configs_id'), table_name='admin_configs')
    op.drop_index(op.f('ix_admin_configs_email'), table_name='admin_configs')
    op.drop_table('admin_configs')
    # ### end Alembic commands ###
